# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_exif_explorer.ipynb.

# %% auto 0
__all__ = ['ImageData', 'path', 'images', 'get_exif', 'extract_exif']

# %% ../01_exif_explorer.ipynb 3
from collections import namedtuple
import glob

from PIL import Image
from PIL.ExifTags import TAGS

# %% ../01_exif_explorer.ipynb 4
# datastructure for image and their exif data

ImageData = namedtuple("ImageData", ["image_path", "exif"])

# %% ../01_exif_explorer.ipynb 5
# get a list of all *.jpg's in our sample dir
path = 'sample-data/vegas/*.jpg'
images = glob.glob(path)

# %% ../01_exif_explorer.ipynb 7
def get_exif(image_path):
  i = Image.open(image_path)
  info = i._getexif()
  return {TAGS.get(tag): value for tag, value in info.items()}

# %% ../01_exif_explorer.ipynb 9
def extract_exif(images):
    return [ImageData(i, get_exif(i)) for i in images]
